### ISSUE TITLE
Future Minecraft/FAPI version support

### ISSUE THREAD

**Issue by AzureAaron** [HypixelDev/FabricModAPI#1]
I was wondering how this will be maintained for future Minecraft and Fabric API versions if mods are to rely on this as a dependency. From what I can see there hasn't been any commitments made to keep this library updated and compatible with new Minecraft and Fabric API versions as they become available which can be problematic as many Fabric developers (myself included) want to have working, usable builds of our mods available very soon after updates come out (or even just as they come out) and if the previous builds of this aren't compatible then that could easily cause issues which block development.

It would be great if we can get some clarification on this!

**Comment by ConnorLinfoot** [comment]
Our current goal is to maintain two primary versions of the Mod API:

- One for Forge 1.8.9, as it's currently the most played version on the Hypixel Server, as many are already aware.
- Another for the latest version of Fabric, with the aim of supporting new Minecraft versions as soon as possible. Minor updates will, of course, be quick if any changes are needed at all. But major versions may take a little longer.
  - In some cases, we may support the previous major for a short time after a new major; it would primarily depend on which version players stick to. As an example, when 1.21 releases, we may still update the 1.20.6 version with Mod API changes if we feel it is necessary. But we would encourage developers to try and be on the latest version as best they can. 

It's hard to say for sure how fast we will be updating support as necessary, as it primarily comes down to when those versions release, the changes involved, and if we have someone internally available to make the changes needed. 

We do want to try and keep the implementations as simple as possible to allow faster updates. I'll mention a similar point in your other issue (#2), but currently, with it being so simple, it's unlikely any major changes will occur that will prevent us from updating to new versions quickly.

I will also mention that we are open to community contributions; we don't want it to get too complicated for what it's intended to provide. But if someone in the community adds support for the next version before we do so, we'll happily merge that and release it as soon as possible.
